# Generated by Django 3.1.12 on 2024-12-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_auto_20241227_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=500)),
                ('result', models.CharField(max_length=50)),
            ],
        ),
    ]
