# Generated by Django 3.1.12 on 2024-12-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0004_detection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='detection',
            name='result',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detection',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='detection',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
