# Generated by Django 3.1.12 on 2024-12-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_auto_20241227_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
