# Generated by Django 3.1.12 on 2024-12-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0006_auto_20241227_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='uploads/videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
